spring.application.name=RecipeBook

server.port=8081

# baza danych
spring.datasource.url=jdbc:h2:file:./data/recipedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# h2 konsola
spring.h2.console.enabled=true


spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


springdoc.swagger-ui.path=/swagger-ui.html